# Site settings
title: saved something
email:
description: Community Site
baseurl:
url:
twitter_username:
github_username:  

# Build settings
markdown: kramdown
permalink: pretty
google_analytics: UA-0000000-01
show_downloads: true
theme: jekyll-theme-leap-day